repos:
  - repo: local
    hooks:
      # Ruff代码检查
      - id: ruff-lint
        name: ruff-lint
        language: system
        entry: .venv/bin/ruff check --fix
        types: [python]
        stages: [pre-commit]
        exclude: ^\.venv/
      # Ruff代码格式化
      - id: ruff-format
        name: ruff-format
        language: system
        entry: .venv/bin/ruff format
        types: [python]
        stages: [pre-commit]
        exclude: ^\.venv/

  - repo: local
    hooks:
      - id: mypy
        name: mypy-type-check
        language: system
        entry: .venv/bin/mypy
        args: [--config-file=pyproject.toml]
        types: [python]
        stages: [pre-commit]
        exclude: ^\.venv/